# Generated by Django 4.2.4 on 2023-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_review_author_alter_review_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="archived",
        ),
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
