# Generated by Django 4.2.4 on 2023-08-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_archived_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='date',
        ),
    ]
