# Generated by Django 4.2.4 on 2023-08-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
        migrations.AddField(
            model_name="specifications",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.product",
                verbose_name="Продукты",
            ),
            preserve_default=False,
        ),
    ]
