# Generated by Django 4.2.4 on 2023-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_product_specifications_specifications_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specifications",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specifications",
                to="product.product",
                verbose_name="Продукты",
            ),
        ),
    ]
