# Generated by Django 4.2.4 on 2023-09-02 06:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_alter_sale_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Картинка товара",
                "verbose_name_plural": "Картинки товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "verbose_name": "Скидка товара",
                "verbose_name_plural": "Скидки товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="specifications",
            options={
                "verbose_name": "Спецификация",
                "verbose_name_plural": "Спецификации",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="sorted_index",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Индекс сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="dateFrom",
            field=models.DateTimeField(
                default="", verbose_name="Дата окончания скидки"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала скидки"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_products",
                to="product.product",
                verbose_name="Продукт",
            ),
        ),
    ]
