# Generated by Django 4.2.4 on 2023-09-02 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countproductinorder",
            options={
                "verbose_name": "Продукт-заказ",
                "verbose_name_plural": "Продукты-заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
    ]
