# Generated by Django 4.2.4 on 2023-08-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
